export const data = [
  {
    src: "/images/pizza-background.jpg",
    classGit: "link-icon-github",
    hrefGit: "https://github.com/GalPalas/pizza-website",
    target: "_blank",
    rel: "noreferrer",
    iconGit: "bx bxl-github",
    classGlobe: "link-icon-globe",
    hrefGlobe: "https://gal-pizza-planet.netlify.app/",
    iconGlobe: "bx bx-globe",
  },
  {
    src: "/images/travel-background.jpg",
    classGit: "link-icon-github",
    hrefGit: "https://github.com/GalPalas/travel-website",
    target: "_blank",
    rel: "noreferrer",
    iconGit: "bx bxl-github",
    classGlobe: "link-icon-globe",
    hrefGlobe: "https://gal-travel.netlify.app",
    iconGlobe: "bx bx-globe",
  },
  {
    src: "/images/shopping-cart-background.jpg",
    classGit: "link-icon-github",
    hrefGit: "https://github.com/GalPalas/shopping-cart-website",
    target: "_blank",
    rel: "noreferrer",
    iconGit: "bx bxl-github",
    classGlobe: "link-icon-globe",
    hrefGlobe: "https://galpalas-shopping-cart.netlify.app/",
    iconGlobe: "bx bx-globe",
  },
  {
    src: "/images/vidly-background.jpg",
    classGit: "link-icon-github",
    hrefGit: "https://github.com/GalPalas/Vidly-FrontEnd",
    target: "_blank",
    rel: "noreferrer",
    iconGit: "bx bxl-github",
    classGlobe: "link-icon-globe",
    hrefGlobe: "https://gal-vidly.netlify.app/movies",
    iconGlobe: "bx bx-globe",
  },
  {
    src: "/images/work5.jpg",
    classGit: "link-icon-github",
    hrefGit: "",
    target: "_blank",
    rel: "noreferrer",
    iconGit: "bx bxl-github",
    classGlobe: "link-icon-globe",
    hrefGlobe: "",
    iconGlobe: "bx bx-globe",
  },
  {
    src: "/images/work6.jpg",
    classGit: "link-icon-github",
    hrefGit: "",
    target: "_blank",
    rel: "noreferrer",
    iconGit: "bx bxl-github",
    classGlobe: "link-icon-globe",
    hrefGlobe: "",
    iconGlobe: "bx bx-globe",
  },
];
